//go:build linux

package dns

import (
	"fmt"
	"os"
)

const resolvConf = "/etc/resolv.conf"

// Override rewrites /etc/resolv.conf to point at our DNS resolver.
// It saves the original content so it can be restored.
func Override(listenAddr string) (restore func() error, err error) {
	original, err := os.ReadFile(resolvConf)
	if err != nil {
		return nil, fmt.Errorf("read resolv.conf: %w", err)
	}

	// Extract just the IP from listenAddr (strip port).
	ip := listenAddr
	for i := len(listenAddr) - 1; i >= 0; i-- {
		if listenAddr[i] == ':' {
			ip = listenAddr[:i]
			break
		}
	}

	newContent := fmt.Sprintf("# Generated by karadul — do not edit\nnameserver %s\n", ip)
	if err := os.WriteFile(resolvConf, []byte(newContent), 0644); err != nil {
		return nil, fmt.Errorf("write resolv.conf: %w", err)
	}

	restore = func() error {
		return os.WriteFile(resolvConf, original, 0644)
	}
	return restore, nil
}
